test: data

dbi:
    user: zonestat
    host: "127.0.0.1"

couchdb:
    url: "http://127.0.0.1:5984/"
    username: ~
    password: ~
    dbprefix: "zstat"

daemon:
    geoip: "t/config/GeoLiteCity.dat"